;;;; corpus.lisp — dwightaspencer.com posts as Prolog facts
;;;; Auto-generated by Hugo 0.129.0 on 2026-06-07
;;;; Source: hugo/layouts/index.lisp + hugo/data/author.yaml + hugo/content/posts/
;;;;
;;;; Do not edit directly — update hugo/data/author.yaml or post front matter.
;;;; Regenerate: hugo --gc (runs on every site build)
;;;;
;;;; This file implements the com.dwightaspencer/corpus package (see package.lisp).
;;;; It is loaded as part of the DwightASpencerCom ASDF system:
;;;;
;;;;   (ql-dist:install-dist "http://dwightaspencer.com/distinfo.txt" :prompt nil)
;;;;   (ql:quickload :DwightASpencerCom)
;;;;
;;;; Public entry points are in dwightaspencer.lisp (DwightASpencerCom package):
;;;;   (DwightASpencerCom:query '(tag ?s :privacy))
;;;;   (DwightASpencerCom:find-post "03-rules-types-and-glue")
;;;;   (DwightASpencerCom:all-posts)
;;;;
;;;; Within com.dwightaspencer/corpus, com.dwightaspencer/logic is available as the local nickname 'logic'
;;;; per (:local-nicknames (#:logic #:com.dwightaspencer/logic)) in package.lisp.

(named-readtables:in-readtable :standard)
(in-package #:com.dwightaspencer/corpus)

(defparameter +dist-root+    "https://dwightaspencer.com")
(defparameter +search-index+ "https://dwightaspencer.com/pagefind/pagefind.js")
(defparameter +corpus-url+   "https://dwightaspencer.com/corpus.lisp")
(defparameter +build-date+   "2026-06-07")

;;;; ── Fact assertion ──────────────────────────────────────────────────────────
;;;; Fact schemas (mirrors ml-prolog-pokemon catalog approach):
;;;;   (post   slug title date word-count)
;;;;   (tag    slug keyword)
;;;;   (author slug orcid)
;;;;   (artifact name descriptor path)   ; Easter egg / metadata artifacts
;;;;   (diagram slug index title alt-text) ; Mermaid diagrams embedded in post
;;;;   (related  slug target label)          ; related_post front matter cross-reference
;;;;   (page     slug title section date)    ; all non-post pages (policy, now, uses, etc.)

(defun assert-post-facts (db)
  "Assert all post, tag, author, and artifact facts into DB.
   DB must be a prolog-db created by logic:make-post-kb.
   Returns DB.
   Generated from 20 posts."
  ;; pf = assert a prolog fact into db (shorthand for logic:db-assert)
  (flet ((pf (&rest fact) (logic:db-assert db fact)))

    ;; The SADM Incident Is an OT Visibility Story
    (pf 'post "20-sadm-ot-visibility"
        "The SADM Incident Is an OT Visibility Story"
        "2026-06-07"
        1096)
(pf 'tag "20-sadm-ot-visibility" :ot)
(pf 'tag "20-sadm-ot-visibility" :ics)
(pf 'tag "20-sadm-ot-visibility" :infrastructure)
(pf 'tag "20-sadm-ot-visibility" :security)
(pf 'author "20-sadm-ot-visibility" "0009-0001-0066-4646")

    ;; Your SBOM Does Not Know Copilot Wrote That Function
    (pf 'post "14-sbom-ai-provenance"
        "Your SBOM Does Not Know Copilot Wrote That Function"
        "2026-06-04"
        590)
(pf 'tag "14-sbom-ai-provenance" :devsecops)
(pf 'tag "14-sbom-ai-provenance" :infosec)
(pf 'tag "14-sbom-ai-provenance" :devops)
(pf 'author "14-sbom-ai-provenance" "0009-0001-0066-4646")
(pf 'related "14-sbom-ai-provenance"
        "13-copilot-meter-governance"
        "Yesterday: the Copilot billing change is a governance problem")

    ;; AI Slop and the Missing Audit Trail Are the Same Bug
    (pf 'post "16-ai-slop-audit-trail"
        "AI Slop and the Missing Audit Trail Are the Same Bug"
        "2026-06-04"
        1126)
(pf 'tag "16-ai-slop-audit-trail" :devsecops)
(pf 'tag "16-ai-slop-audit-trail" :infosec)
(pf 'tag "16-ai-slop-audit-trail" :devops)
(pf 'author "16-ai-slop-audit-trail" "0009-0001-0066-4646")
(pf 'related "16-ai-slop-audit-trail"
        "14-sbom-ai-provenance"
        "post 12b: your SBOM does not know Copilot wrote that function")

    ;; The Copilot Meter Shock Is a Governance Problem
    (pf 'post "13-copilot-meter-governance"
        "The Copilot Meter Shock Is a Governance Problem"
        "2026-06-03"
        474)
(pf 'tag "13-copilot-meter-governance" :devops)
(pf 'tag "13-copilot-meter-governance" :infosec)
(pf 'tag "13-copilot-meter-governance" :cloudnative)
(pf 'author "13-copilot-meter-governance" "0009-0001-0066-4646")
(pf 'related "13-copilot-meter-governance"
        "14-sbom-ai-provenance"
        "Tomorrow: your SBOM doesn't know Copilot wrote that function")

    ;; Owning Your Memory: Hardened Arenas, Channels, and Structural OOP in Pure C99
    (pf 'post "12-owning-your-memory"
        "Owning Your Memory: Hardened Arenas, Channels, and Structural OOP in Pure C99"
        "2026-05-29"
        1811)
(pf 'tag "12-owning-your-memory" :c99)
(pf 'tag "12-owning-your-memory" :systems)
(pf 'tag "12-owning-your-memory" :devops)
(pf 'tag "12-owning-your-memory" :infosec)
(pf 'tag "12-owning-your-memory" :architecture)
(pf 'tag "12-owning-your-memory" :open-source)
(pf 'tag "12-owning-your-memory" :privacy)
(pf 'tag "12-owning-your-memory" :sovereignty)
(pf 'author "12-owning-your-memory" "0009-0001-0066-4646")
(pf 'diagram "12-owning-your-memory" 0
        "Architecture overview: coding standards, arena, object lifecycle, channel, assert, single-exit"
        "Architecture flowchart for example.c. Four standards layers feed into the implementation: ISO C99, all ten NASA Power of Ten rules, tsoding conventions (Yoda conditions, zero-init arenas), and project rules (no system calls, no goto in C, BDD-first workflow). The static arena holds eight typed slots. Objects are allocated by scanning for a free slot, retained by incrementing a ref_count, and released by decrementing it — zeroing the payload and freeing the slot when the count reaches zero. INVALID_HANDLE is UINT16_MAX. The channel is a ring buffer living in slot zero; send retains and enqueues, recv dequeues and transfers ownership to the caller. Assertions trap via __builtin_trap, which emits ud2 on x86 and raises SIGILL. Single-exit is a do-while-zero loop with break on error; cleanup releases any live handles unconditionally.")
(pf 'related "12-owning-your-memory"
        "03-rules-types-and-glue"
        "post 03 evaluates the same layered-standards approach across Prolog, Coalton, and Common Lisp")

    ;; Chatrie v. United States: The Cloud Storage Question the Supreme Court Has to Answer
    (pf 'post "18-chatrie-geofence"
        "Chatrie v. United States: The Cloud Storage Question the Supreme Court Has to Answer"
        "2026-05-28"
        822)
(pf 'tag "18-chatrie-geofence" :fourth-amendment)
(pf 'tag "18-chatrie-geofence" :privacy)
(pf 'tag "18-chatrie-geofence" :civil-liberties)
(pf 'tag "18-chatrie-geofence" :surveillance)
(pf 'author "18-chatrie-geofence" "0009-0001-0066-4646")
(pf 'related "18-chatrie-geofence"
        "17-troy-flock"
        "post 13 covers the municipal procurement side of the same infrastructure")

    ;; Troy, NY: How a Surveillance Contract Captured a City
    (pf 'post "17-troy-flock"
        "Troy, NY: How a Surveillance Contract Captured a City"
        "2026-05-27"
        1076)
(pf 'tag "17-troy-flock" :privacy)
(pf 'tag "17-troy-flock" :surveillance)
(pf 'tag "17-troy-flock" :fourth-amendment)
(pf 'tag "17-troy-flock" :civil-liberties)
(pf 'author "17-troy-flock" "0009-0001-0066-4646")
(pf 'related "17-troy-flock"
        "06-fourth-amendment-ai-surveillance"
        "post 06 covers the Fourth Amendment framework this contract operates inside")

    ;; neural.sh: A Shell Script Where a Plugin Used to Be
    (pf 'post "11-neural-sh"
        "neural.sh: A Shell Script Where a Plugin Used to Be"
        "2026-05-26"
        631)
(pf 'tag "11-neural-sh" :infrastructure)
(pf 'tag "11-neural-sh" :open-source)
(pf 'tag "11-neural-sh" :privacy)
(pf 'tag "11-neural-sh" :history)
(pf 'author "11-neural-sh" "0009-0001-0066-4646")
(pf 'related "11-neural-sh"
        "12-owning-your-memory"
        "post 12 covers the same constraint-as-design argument applied to C99 memory management")

    ;; LLM-Generated Terraform Does Not Know What Your Architecture Is For
    (pf 'post "15-terraform-llm-thesis"
        "LLM-Generated Terraform Does Not Know What Your Architecture Is For"
        "2026-05-26"
        758)
(pf 'tag "15-terraform-llm-thesis" :infrastructure)
(pf 'tag "15-terraform-llm-thesis" :devops)
(pf 'tag "15-terraform-llm-thesis" :open-source)
(pf 'author "15-terraform-llm-thesis" "0009-0001-0066-4646")
(pf 'related "15-terraform-llm-thesis"
        "11-neural-sh"
        "post 11 covers the Unix shell approach to the same LLM tooling problem")

    ;; Three Runtimes, One Site: A Case for Self-Documenting Infrastructure
    (pf 'post "10-three-runtimes-one-site"
        "Three Runtimes, One Site: A Case for Self-Documenting Infrastructure"
        "2026-05-24"
        1478)
(pf 'tag "10-three-runtimes-one-site" :infrastructure)
(pf 'tag "10-three-runtimes-one-site" :open-source)
(pf 'tag "10-three-runtimes-one-site" :architecture)
(pf 'tag "10-three-runtimes-one-site" :lisp)
(pf 'author "10-three-runtimes-one-site" "0009-0001-0066-4646")
(pf 'related "10-three-runtimes-one-site"
        "03-rules-types-and-glue"
        "post 03 covers the logic engine architecture in the Pokémon study context")

    ;; The Watchers You Fed: Chapter Preview
    (pf 'post "04-watchers-you-fed"
        "The Watchers You Fed: Chapter Preview"
        "2026-05-23"
        746)
(pf 'tag "04-watchers-you-fed" :surveillance)
(pf 'tag "04-watchers-you-fed" :privacy)
(pf 'tag "04-watchers-you-fed" :fourth-amendment)
(pf 'author "04-watchers-you-fed" "0009-0001-0066-4646")

    ;; The Shell Is Gone (For Now)
    (pf 'post "08-the-shell-is-gone"
        "The Shell Is Gone (For Now)"
        "2026-05-23"
        432)
(pf 'tag "08-the-shell-is-gone" :infrastructure)
(pf 'tag "08-the-shell-is-gone" :self-hosting)
(pf 'tag "08-the-shell-is-gone" :write-ups)
(pf 'author "08-the-shell-is-gone" "0009-0001-0066-4646")
(pf 'related "08-the-shell-is-gone"
        "05-infrastructure-independence"
        "post 05 covers the philosophy in more depth")

    ;; Infrastructure Independence: Self-Hosting Without the Hype
    (pf 'post "05-infrastructure-independence"
        "Infrastructure Independence: Self-Hosting Without the Hype"
        "2026-05-23"
        1360)
(pf 'tag "05-infrastructure-independence" :self-hosting)
(pf 'tag "05-infrastructure-independence" :infrastructure)
(pf 'tag "05-infrastructure-independence" :privacy)
(pf 'tag "05-infrastructure-independence" :devops)
(pf 'author "05-infrastructure-independence" "0009-0001-0066-4646")

    ;; Fourth Amendment in the Age of AI Surveillance
    (pf 'post "06-fourth-amendment-ai-surveillance"
        "Fourth Amendment in the Age of AI Surveillance"
        "2026-05-23"
        980)
(pf 'tag "06-fourth-amendment-ai-surveillance" :fourth-amendment)
(pf 'tag "06-fourth-amendment-ai-surveillance" :surveillance)
(pf 'tag "06-fourth-amendment-ai-surveillance" :privacy)
(pf 'tag "06-fourth-amendment-ai-surveillance" :civil-liberties)
(pf 'author "06-fourth-amendment-ai-surveillance" "0009-0001-0066-4646")

    ;; DevOps Before DevOps: The 2007–2008 IBM IP Dispute and What It Means Now
    (pf 'post "07-devops-before-devops"
        "DevOps Before DevOps: The 2007–2008 IBM IP Dispute and What It Means Now"
        "2026-05-23"
        810)
(pf 'tag "07-devops-before-devops" :devops)
(pf 'tag "07-devops-before-devops" :history)
(pf 'tag "07-devops-before-devops" :open-source)
(pf 'author "07-devops-before-devops" "0009-0001-0066-4646")

    ;; After the Canary: What Happened to the Warrant Canary Standard
    (pf 'post "09-after-the-canary"
        "After the Canary: What Happened to the Warrant Canary Standard"
        "2026-05-23"
        971)
(pf 'tag "09-after-the-canary" :privacy)
(pf 'tag "09-after-the-canary" :surveillance)
(pf 'tag "09-after-the-canary" :open-source)
(pf 'tag "09-after-the-canary" :infrastructure)
(pf 'author "09-after-the-canary" "0009-0001-0066-4646")
(pf 'related "09-after-the-canary"
        "01-a-better-tweedy-bird"
        "post 01 has the original canary architecture argument")

    ;; Rules, Types, and Glue: A Multi-Paradigm Architecture for Game Simulation
    (pf 'post "03-rules-types-and-glue"
        "Rules, Types, and Glue: A Multi-Paradigm Architecture for Game Simulation"
        "2026-05-22"
        2225)
(pf 'tag "03-rules-types-and-glue" :architecture)
(pf 'tag "03-rules-types-and-glue" :common-lisp)
(pf 'tag "03-rules-types-and-glue" :prolog)
(pf 'tag "03-rules-types-and-glue" :open-source)
(pf 'author "03-rules-types-and-glue" "0009-0001-0066-4646")
(pf 'related "03-rules-types-and-glue"
        "12-owning-your-memory"
        "post 12 applies the same constraint-as-design principle to C99 arena allocation")

    ;; GitHub's TOS Won't Save You: Why Your Code, Privacy & Copyrights Are at Risk
    (pf 'post "02-github-tos-wont-save-you"
        "GitHub's TOS Won't Save You: Why Your Code, Privacy & Copyrights Are at Risk"
        "2026-03-11"
        2188)
(pf 'tag "02-github-tos-wont-save-you" :github)
(pf 'tag "02-github-tos-wont-save-you" :sourcehut)
(pf 'tag "02-github-tos-wont-save-you" :privacy)
(pf 'tag "02-github-tos-wont-save-you" :copyright)
(pf 'tag "02-github-tos-wont-save-you" :ai-training)
(pf 'tag "02-github-tos-wont-save-you" :copilot)
(pf 'tag "02-github-tos-wont-save-you" :foss)
(pf 'author "02-github-tos-wont-save-you" "0009-0001-0066-4646")

    ;; Privacy Canaries: A Better Tweedy Bird
    (pf 'post "01-a-better-tweedy-bird"
        "Privacy Canaries: A Better Tweedy Bird"
        "2025-01-20"
        839)
(pf 'tag "01-a-better-tweedy-bird" :privacy)
(pf 'tag "01-a-better-tweedy-bird" :surveillance)
(pf 'tag "01-a-better-tweedy-bird" :open-source)
(pf 'author "01-a-better-tweedy-bird" "0009-0001-0066-4646")

    ;; 00 Hellowrld
    (pf 'post "00-hellowrld"
        "00 Hellowrld"
        "2025-01-07"
        114)
(pf 'tag "00-hellowrld" :write-ups)
(pf 'author "00-hellowrld" "0009-0001-0066-4646")




  )
  db)

;;;; ── Knowledge base construction ────────────────────────────────────────────

(defun make-site-kb ()
  "Construct and return the site knowledge base.
   Asserts all post/tag/author facts plus static artifact facts.
   Called by DwightASpencerCom:make-kb in dwightaspencer.lisp —
   use that for the public API rather than calling this directly.
   Returns the populated prolog-db."
  (let ((db (assert-post-facts (logic:make-post-kb))))
    ;; ── Static artifact facts ────────────────────────────────────────────────
    ;; These are not generated from post front matter — they are manually
    ;; asserted here. Discoverable via: (DwightASpencerCom:query '(tag ?s :bbs))
    ;;
    ;; /.well-known/file_id.diz — raw ANSI splash from XM Core BBS
    ;; SAUCE header intact. IBM VGA. 20160503. dz tag. It is well known.
    (logic:db-assert db '(artifact "file_id.diz" :bbs-descriptor "/.well-known/file_id.diz"))
    (logic:db-assert db '(tag "file_id.diz" :bbs))
    (logic:db-assert db '(tag "file_id.diz" :ansi-art))
    db))

;;;; ── Corpus query functions ──────────────────────────────────────────────────
;;;; These take an explicit KB argument — they are the corpus layer's API.
;;;; The DwightASpencerCom package wraps these with a *kb* cache and
;;;; single-argument convenience functions (see dwightaspencer.lisp).

(defun find-post (kb slug)
  "Return a plist for post SLUG in KB, or NIL if not found.
   Plist keys: :slug :title :date :words"
  (let ((env (logic:db-prove-first kb `(post ,slug ?title ?date ?wc))))
    (when env
      (list :slug  slug
            :title (cdr (assoc '?title env))
            :date  (cdr (assoc '?date  env))
            :words (cdr (assoc '?wc    env))))))

(defun find-by-tag (kb tag)
  "Return a list of post slugs tagged with TAG in KB.
   TAG should be a keyword, e.g. :privacy, :bbs, :ansi-art"
  (logic:db-var-all kb `(tag ?slug ,tag) '?slug))

(defun all-posts (kb)
  "Return a list of all post slugs in KB."
  (logic:db-var-all kb '(post ?slug ?title ?date ?wc) '?slug))

(defun all-tags (kb)
  "Return a deduplicated list of all tag keywords in KB."
  (remove-duplicates
   (logic:db-var-all kb '(tag ?slug ?tag) '?tag)
   :test #'equal))

(defun post-diagrams (kb slug)
  "Return a list of diagram plists for post SLUG in KB.
   Each plist has keys: :index :title :alt
   Returns NIL if the post has no diagrams."
  (mapcar (lambda (env)
            (list :index (cdr (assoc '?i   env))
                  :title (cdr (assoc '?t   env))
                  :alt   (cdr (assoc '?alt env))))
          (logic:db-prove-all kb `(diagram ,slug ?i ?t ?alt))))

(defun all-diagrams (kb)
  "Return a list of all diagram facts in KB as plists.
   Keys: :slug :index :title :alt"
  (mapcar (lambda (env)
            (list :slug  (cdr (assoc '?slug env))
                  :index (cdr (assoc '?i    env))
                  :title (cdr (assoc '?t    env))
                  :alt   (cdr (assoc '?alt  env))))
          (logic:db-prove-all kb '(diagram ?slug ?i ?t ?alt))))

(defun post-related (kb slug)
  "Return a plist for the related post of SLUG in KB, or NIL.
   Plist keys: :target :label
   Only returns a value if SLUG has a related_post front matter entry."
  (let ((env (logic:db-prove-first kb `(related ,slug ?target ?label))))
    (when env
      (list :target (cdr (assoc '?target env))
            :label  (cdr (assoc '?label  env))))))

(defun posts-related-to (kb target-slug)
  "Return a list of slugs whose related_post points at TARGET-SLUG.
   Enables reverse traversal: find all posts that cite a given post."
  (logic:db-var-all kb `(related ?slug ,target-slug ?label) '?slug))

(defun all-related (kb)
  "Return all (related slug target label) facts as plists.
   Keys: :slug :target :label
   Enables full graph traversal of the post relationship network."
  (mapcar (lambda (env)
            (list :slug   (cdr (assoc '?slug   env))
                  :target (cdr (assoc '?target env))
                  :label  (cdr (assoc '?label  env))))
          (logic:db-prove-all kb '(related ?slug ?target ?label))))

(defun all-pages (kb)
  "Return all non-post pages in KB as plists. Keys: :slug :title :section :date"
  (mapcar (lambda (env)
            (list :slug    (cdr (assoc '?slug    env))
                  :title   (cdr (assoc '?title   env))
                  :section (cdr (assoc '?section env))
                  :date    (cdr (assoc '?date    env))))
          (logic:db-prove-all kb '(page ?slug ?title ?section ?date))))

(defun find-page (kb slug)
  "Find a non-post page by slug. Returns plist or NIL."
  (let ((env (logic:db-prove-first kb `(page ,slug ?title ?section ?date))))
    (when env
      (list :slug    slug
            :title   (cdr (assoc '?title   env))
            :section (cdr (assoc '?section env))
            :date    (cdr (assoc '?date    env))))))
