;;;; corpus.lisp — dwightaspencer.com posts as Prolog facts
;;;; Auto-generated by Hugo 0.129.0 on 2026-05-24
;;;; Source: hugo/layouts/index.lisp + hugo/data/author.yaml + hugo/content/posts/
;;;;
;;;; Do not edit directly — update hugo/data/author.yaml or post front matter.
;;;; Regenerate: hugo --gc (runs on every site build)
;;;;
;;;; (ql-dist:install-dist "http://dwightaspencer.com/distinfo.txt" :prompt nil)

(named-readtables:in-readtable :standard)
(in-package #:dsc/corpus)

(defconstant +dist-root+    "https://dwightaspencer.com")
(defconstant +search-index+ "https://dwightaspencer.com/pagefind/pagefind.js")
(defconstant +corpus-url+   "https://dwightaspencer.com/lisp/corpus.lisp")
(defconstant +build-date+   "2026-05-24")

;;;; ── Fact assertion ──────────────────────────────────────────────────────────

(defun assert-post-facts (db)
  "Assert all post/tag/author facts into DB.
   Generated from 10 posts."
  (flet ((pf (&rest fact) (logic:db-assert db fact)))

    ;; The Watchers You Fed: Chapter Preview
    (pf 'post "04-watchers-you-fed"
        "The Watchers You Fed: Chapter Preview"
        "2026-05-23"
        746)
(pf 'tag "04-watchers-you-fed" :surveillance)
(pf 'tag "04-watchers-you-fed" :privacy)
(pf 'tag "04-watchers-you-fed" :fourth-amendment)
(pf 'author "04-watchers-you-fed" "0009-0001-0066-4646")

    ;; The Shell Is Gone (For Now)
    (pf 'post "08-the-shell-is-gone"
        "The Shell Is Gone (For Now)"
        "2026-05-23"
        442)
(pf 'tag "08-the-shell-is-gone" :infrastructure)
(pf 'tag "08-the-shell-is-gone" :self-hosting)
(pf 'tag "08-the-shell-is-gone" :write-ups)
(pf 'author "08-the-shell-is-gone" "0009-0001-0066-4646")

    ;; Infrastructure Independence: Self-Hosting Without the Hype
    (pf 'post "05-infrastructure-independence"
        "Infrastructure Independence: Self-Hosting Without the Hype"
        "2026-05-23"
        1360)
(pf 'tag "05-infrastructure-independence" :self-hosting)
(pf 'tag "05-infrastructure-independence" :infrastructure)
(pf 'tag "05-infrastructure-independence" :privacy)
(pf 'tag "05-infrastructure-independence" :devops)
(pf 'author "05-infrastructure-independence" "0009-0001-0066-4646")

    ;; Fourth Amendment in the Age of AI Surveillance
    (pf 'post "06-fourth-amendment-ai-surveillance"
        "Fourth Amendment in the Age of AI Surveillance"
        "2026-05-23"
        980)
(pf 'tag "06-fourth-amendment-ai-surveillance" :fourth-amendment)
(pf 'tag "06-fourth-amendment-ai-surveillance" :surveillance)
(pf 'tag "06-fourth-amendment-ai-surveillance" :privacy)
(pf 'tag "06-fourth-amendment-ai-surveillance" :civil-liberties)
(pf 'author "06-fourth-amendment-ai-surveillance" "0009-0001-0066-4646")

    ;; DevOps Before DevOps: The 2007–2008 IBM IP Dispute and What It Means Now
    (pf 'post "07-devops-before-devops"
        "DevOps Before DevOps: The 2007–2008 IBM IP Dispute and What It Means Now"
        "2026-05-23"
        810)
(pf 'tag "07-devops-before-devops" :devops)
(pf 'tag "07-devops-before-devops" :history)
(pf 'tag "07-devops-before-devops" :open-source)
(pf 'author "07-devops-before-devops" "0009-0001-0066-4646")

    ;; After the Canary: What Happened to the Warrant Canary Standard
    (pf 'post "09-after-the-canary"
        "After the Canary: What Happened to the Warrant Canary Standard"
        "2026-05-23"
        789)
(pf 'tag "09-after-the-canary" :privacy)
(pf 'tag "09-after-the-canary" :surveillance)
(pf 'tag "09-after-the-canary" :open-source)
(pf 'tag "09-after-the-canary" :infrastructure)
(pf 'author "09-after-the-canary" "0009-0001-0066-4646")

    ;; Rules, Types, and Glue: A Multi-Paradigm Architecture for Game Simulation
    (pf 'post "03-rules-types-and-glue"
        "Rules, Types, and Glue: A Multi-Paradigm Architecture for Game Simulation"
        "2026-05-22"
        2225)
(pf 'author "03-rules-types-and-glue" "0009-0001-0066-4646")

    ;; GitHub's TOS Won't Save You: Why Your Code, Privacy & Copyrights Are at Risk
    (pf 'post "02-github-tos-wont-save-you"
        "GitHub's TOS Won't Save You: Why Your Code, Privacy & Copyrights Are at Risk"
        "2026-03-11"
        2188)
(pf 'tag "02-github-tos-wont-save-you" :github)
(pf 'tag "02-github-tos-wont-save-you" :sourcehut)
(pf 'tag "02-github-tos-wont-save-you" :privacy)
(pf 'tag "02-github-tos-wont-save-you" :copyright)
(pf 'tag "02-github-tos-wont-save-you" :ai-training)
(pf 'tag "02-github-tos-wont-save-you" :copilot)
(pf 'tag "02-github-tos-wont-save-you" :foss)
(pf 'author "02-github-tos-wont-save-you" "0009-0001-0066-4646")

    ;; Privacy Canaries: A Better Tweedy Bird
    (pf 'post "01-a-better-tweedy-bird"
        "Privacy Canaries: A Better Tweedy Bird"
        "2025-01-20"
        839)
(pf 'tag "01-a-better-tweedy-bird" :privacy)
(pf 'tag "01-a-better-tweedy-bird" :surveillance)
(pf 'tag "01-a-better-tweedy-bird" :open-source)
(pf 'author "01-a-better-tweedy-bird" "0009-0001-0066-4646")

    ;; 00 Hellowrld
    (pf 'post "00-hellowrld"
        "00 Hellowrld"
        "2025-01-07"
        114)
(pf 'tag "00-hellowrld" :write-ups)
(pf 'author "00-hellowrld" "0009-0001-0066-4646")
  )
  db)

;;;; ── Query API ───────────────────────────────────────────────────────────────

(defun make-site-kb ()
  "Create and populate the site knowledge base."
  (assert-post-facts (logic:make-post-kb)))

(defun find-post (kb slug)
  "Return post plist for SLUG or NIL."
  (let ((env (logic:db-prove-first kb `(post ,slug ?title ?date ?wc))))
    (when env
      (list :slug  slug
            :title (cdr (assoc '?title env))
            :date  (cdr (assoc '?date  env))
            :words (cdr (assoc '?wc    env))))))

(defun find-by-tag (kb tag)
  "Return all post slugs with TAG."
  (logic:db-var-all kb `(tag ?slug ,tag) '?slug))

(defun all-posts (kb)
  "Return all post slugs."
  (logic:db-var-all kb '(post ?slug ?title ?date ?wc) '?slug))

(defun all-tags (kb)
  "Return all unique tags."
  (remove-duplicates
   (logic:db-var-all kb '(tag ?slug ?tag) '?tag)
   :test #'equal))
