;;;; corpus.lisp — dwightaspencer.com posts as Prolog facts
;;;; Auto-generated by Hugo 0.129.0 on 2026-05-27
;;;; Source: hugo/layouts/index.lisp + hugo/data/author.yaml + hugo/content/posts/
;;;;
;;;; Do not edit directly — update hugo/data/author.yaml or post front matter.
;;;; Regenerate: hugo --gc (runs on every site build)
;;;;
;;;; This file implements the dsc/corpus package (see package.lisp).
;;;; It is loaded as part of the DwightASpencerCom ASDF system:
;;;;
;;;;   (ql-dist:install-dist "http://dwightaspencer.com/distinfo.txt" :prompt nil)
;;;;   (ql:quickload :DwightASpencerCom)
;;;;
;;;; Public entry points are in dwightaspencer.lisp (DwightASpencerCom package):
;;;;   (DwightASpencerCom:query '(tag ?s :privacy))
;;;;   (DwightASpencerCom:find-post "03-rules-types-and-glue")
;;;;   (DwightASpencerCom:all-posts)
;;;;
;;;; Within dsc/corpus, dsc/logic is available as the local nickname 'logic'
;;;; per (:local-nicknames (#:logic #:dsc/logic)) in package.lisp.

(named-readtables:in-readtable :standard)
(in-package #:dsc/corpus)

(defconstant +dist-root+    "https://dwightaspencer.com")
(defconstant +search-index+ "https://dwightaspencer.com/pagefind/pagefind.js")
(defconstant +corpus-url+   "https://dwightaspencer.com/corpus.lisp")
(defconstant +build-date+   "2026-05-27")

;;;; ── Fact assertion ──────────────────────────────────────────────────────────
;;;; Fact schemas (mirrors ml-prolog-pokemon catalog approach):
;;;;   (post   slug title date word-count)
;;;;   (tag    slug keyword)
;;;;   (author slug orcid)
;;;;   (artifact name descriptor path)   ; Easter egg / metadata artifacts

(defun assert-post-facts (db)
  "Assert all post, tag, author, and artifact facts into DB.
   DB must be a prolog-db created by logic:make-post-kb.
   Returns DB.
   Generated from 10 posts."
  ;; pf = assert a prolog fact into db (shorthand for logic:db-assert)
  (flet ((pf (&rest fact) (logic:db-assert db fact)))

    ;; The Watchers You Fed: Chapter Preview
    (pf 'post "04-watchers-you-fed"
        "The Watchers You Fed: Chapter Preview"
        "2026-05-23"
        746)
(pf 'tag "04-watchers-you-fed" :surveillance)
(pf 'tag "04-watchers-you-fed" :privacy)
(pf 'tag "04-watchers-you-fed" :fourth-amendment)
(pf 'author "04-watchers-you-fed" "0009-0001-0066-4646")

    ;; The Shell Is Gone (For Now)
    (pf 'post "08-the-shell-is-gone"
        "The Shell Is Gone (For Now)"
        "2026-05-23"
        442)
(pf 'tag "08-the-shell-is-gone" :infrastructure)
(pf 'tag "08-the-shell-is-gone" :self-hosting)
(pf 'tag "08-the-shell-is-gone" :write-ups)
(pf 'author "08-the-shell-is-gone" "0009-0001-0066-4646")

    ;; Infrastructure Independence: Self-Hosting Without the Hype
    (pf 'post "05-infrastructure-independence"
        "Infrastructure Independence: Self-Hosting Without the Hype"
        "2026-05-23"
        1360)
(pf 'tag "05-infrastructure-independence" :self-hosting)
(pf 'tag "05-infrastructure-independence" :infrastructure)
(pf 'tag "05-infrastructure-independence" :privacy)
(pf 'tag "05-infrastructure-independence" :devops)
(pf 'author "05-infrastructure-independence" "0009-0001-0066-4646")

    ;; Fourth Amendment in the Age of AI Surveillance
    (pf 'post "06-fourth-amendment-ai-surveillance"
        "Fourth Amendment in the Age of AI Surveillance"
        "2026-05-23"
        980)
(pf 'tag "06-fourth-amendment-ai-surveillance" :fourth-amendment)
(pf 'tag "06-fourth-amendment-ai-surveillance" :surveillance)
(pf 'tag "06-fourth-amendment-ai-surveillance" :privacy)
(pf 'tag "06-fourth-amendment-ai-surveillance" :civil-liberties)
(pf 'author "06-fourth-amendment-ai-surveillance" "0009-0001-0066-4646")

    ;; DevOps Before DevOps: The 2007–2008 IBM IP Dispute and What It Means Now
    (pf 'post "07-devops-before-devops"
        "DevOps Before DevOps: The 2007–2008 IBM IP Dispute and What It Means Now"
        "2026-05-23"
        810)
(pf 'tag "07-devops-before-devops" :devops)
(pf 'tag "07-devops-before-devops" :history)
(pf 'tag "07-devops-before-devops" :open-source)
(pf 'author "07-devops-before-devops" "0009-0001-0066-4646")

    ;; After the Canary: What Happened to the Warrant Canary Standard
    (pf 'post "09-after-the-canary"
        "After the Canary: What Happened to the Warrant Canary Standard"
        "2026-05-23"
        981)
(pf 'tag "09-after-the-canary" :privacy)
(pf 'tag "09-after-the-canary" :surveillance)
(pf 'tag "09-after-the-canary" :open-source)
(pf 'tag "09-after-the-canary" :infrastructure)
(pf 'author "09-after-the-canary" "0009-0001-0066-4646")

    ;; Rules, Types, and Glue: A Multi-Paradigm Architecture for Game Simulation
    (pf 'post "03-rules-types-and-glue"
        "Rules, Types, and Glue: A Multi-Paradigm Architecture for Game Simulation"
        "2026-05-22"
        2225)
(pf 'tag "03-rules-types-and-glue" :architecture)
(pf 'tag "03-rules-types-and-glue" :common-lisp)
(pf 'tag "03-rules-types-and-glue" :prolog)
(pf 'tag "03-rules-types-and-glue" :open-source)
(pf 'author "03-rules-types-and-glue" "0009-0001-0066-4646")

    ;; GitHub's TOS Won't Save You: Why Your Code, Privacy & Copyrights Are at Risk
    (pf 'post "02-github-tos-wont-save-you"
        "GitHub's TOS Won't Save You: Why Your Code, Privacy & Copyrights Are at Risk"
        "2026-03-11"
        2188)
(pf 'tag "02-github-tos-wont-save-you" :github)
(pf 'tag "02-github-tos-wont-save-you" :sourcehut)
(pf 'tag "02-github-tos-wont-save-you" :privacy)
(pf 'tag "02-github-tos-wont-save-you" :copyright)
(pf 'tag "02-github-tos-wont-save-you" :ai-training)
(pf 'tag "02-github-tos-wont-save-you" :copilot)
(pf 'tag "02-github-tos-wont-save-you" :foss)
(pf 'author "02-github-tos-wont-save-you" "0009-0001-0066-4646")

    ;; Privacy Canaries: A Better Tweedy Bird
    (pf 'post "01-a-better-tweedy-bird"
        "Privacy Canaries: A Better Tweedy Bird"
        "2025-01-20"
        839)
(pf 'tag "01-a-better-tweedy-bird" :privacy)
(pf 'tag "01-a-better-tweedy-bird" :surveillance)
(pf 'tag "01-a-better-tweedy-bird" :open-source)
(pf 'author "01-a-better-tweedy-bird" "0009-0001-0066-4646")

    ;; 00 Hellowrld
    (pf 'post "00-hellowrld"
        "00 Hellowrld"
        "2025-01-07"
        114)
(pf 'tag "00-hellowrld" :write-ups)
(pf 'author "00-hellowrld" "0009-0001-0066-4646")
  )
  db)

;;;; ── Knowledge base construction ────────────────────────────────────────────

(defun make-site-kb ()
  "Construct and return the site knowledge base.
   Asserts all post/tag/author facts plus static artifact facts.
   Called by DwightASpencerCom:make-kb in dwightaspencer.lisp —
   use that for the public API rather than calling this directly.
   Returns the populated prolog-db."
  (let ((db (assert-post-facts (logic:make-post-kb))))
    ;; ── Static artifact facts ────────────────────────────────────────────────
    ;; These are not generated from post front matter — they are manually
    ;; asserted here. Discoverable via: (DwightASpencerCom:query '(tag ?s :bbs))
    ;;
    ;; /.well-known/file_id.diz — raw ANSI splash from XM Core BBS
    ;; SAUCE header intact. IBM VGA. 20160503. dz tag. It is well known.
    (logic:db-assert db '(artifact "file_id.diz" :bbs-descriptor "/.well-known/file_id.diz"))
    (logic:db-assert db '(tag "file_id.diz" :bbs))
    (logic:db-assert db '(tag "file_id.diz" :ansi-art))
    db))

;;;; ── Corpus query functions ──────────────────────────────────────────────────
;;;; These take an explicit KB argument — they are the corpus layer's API.
;;;; The DwightASpencerCom package wraps these with a *kb* cache and
;;;; single-argument convenience functions (see dwightaspencer.lisp).

(defun find-post (kb slug)
  "Return a plist for post SLUG in KB, or NIL if not found.
   Plist keys: :slug :title :date :words"
  (let ((env (logic:db-prove-first kb `(post ,slug ?title ?date ?wc))))
    (when env
      (list :slug  slug
            :title (cdr (assoc '?title env))
            :date  (cdr (assoc '?date  env))
            :words (cdr (assoc '?wc    env))))))

(defun find-by-tag (kb tag)
  "Return a list of post slugs tagged with TAG in KB.
   TAG should be a keyword, e.g. :privacy, :bbs, :ansi-art"
  (logic:db-var-all kb `(tag ?slug ,tag) '?slug))

(defun all-posts (kb)
  "Return a list of all post slugs in KB."
  (logic:db-var-all kb '(post ?slug ?title ?date ?wc) '?slug))

(defun all-tags (kb)
  "Return a deduplicated list of all tag keywords in KB."
  (remove-duplicates
   (logic:db-var-all kb '(tag ?slug ?tag) '?tag)
   :test #'equal))
