;;;; corpus.lisp — dwightaspencer.com posts as Prolog facts
;;;; Auto-generated by Hugo {{ hugo.Version }} on {{ now.Format "2006-01-02" }}
;;;; Source: hugo/layouts/index.lisp + hugo/data/author.yaml + hugo/content/posts/
;;;;
;;;; Do not edit directly — update hugo/data/author.yaml or post front matter.
;;;; Regenerate: hugo --gc (runs on every site build)
;;;;
;;;; (ql-dist:install-dist "http://dwightaspencer.com/distinfo.txt" :prompt nil)

(named-readtables:in-readtable :standard)
(in-package #:dsc/corpus)

(defconstant +dist-root+    "{{ .Site.Params.canonicalBase }}")
(defconstant +search-index+ "{{ .Site.Params.canonicalBase }}/pagefind/pagefind.js")
(defconstant +corpus-url+   "{{ .Site.Params.canonicalBase }}/corpus.lisp")
(defconstant +build-date+   "{{ now.Format "2006-01-02" }}")

;;;; ── Fact assertion ──────────────────────────────────────────────────────────

(defun assert-post-facts (db)
  "Assert all post/tag/author facts into DB.
   Generated from {{ len (where .Site.RegularPages "Section" "posts") }} posts."
  (flet ((pf (&rest fact) (logic:db-assert db fact)))
{{ range (where .Site.RegularPages "Section" "posts").ByDate.Reverse -}}
{{- $slug := .Slug }}
    ;; {{ .Title }}
    (pf 'post {{ printf "%q" $slug }}
        {{ printf "%q" .Title }}
        {{ printf "%q" (.Date.Format "2006-01-02") }}
        {{ .WordCount }})
{{ range .Params.tags -}}
    (pf 'tag {{ printf "%q" $slug }} :{{ . | lower | replaceRE "[^a-z0-9]" "-" }})
{{ end -}}
    (pf 'author {{ printf "%q" $slug }} "{{ $.Site.Data.author.orcid }}")
{{ end }}  )
  db)

;;;; ── Query API ───────────────────────────────────────────────────────────────

(defun make-site-kb ()
  "Create and populate the site knowledge base."
  (assert-post-facts (logic:make-post-kb)))

(defun find-post (kb slug)
  "Return post plist for SLUG or NIL."
  (let ((env (logic:db-prove-first kb `(post ,slug ?title ?date ?wc))))
    (when env
      (list :slug  slug
            :title (cdr (assoc '?title env))
            :date  (cdr (assoc '?date  env))
            :words (cdr (assoc '?wc    env))))))

(defun find-by-tag (kb tag)
  "Return all post slugs with TAG."
  (logic:db-var-all kb `(tag ?slug ,tag) '?slug))

(defun all-posts (kb)
  "Return all post slugs."
  (logic:db-var-all kb '(post ?slug ?title ?date ?wc) '?slug))

(defun all-tags (kb)
  "Return all unique tags."
  (remove-duplicates
   (logic:db-var-all kb '(tag ?slug ?tag) '?tag)
   :test #'equal))
