;;;; corpus.lisp — dwightaspencer.com posts as Prolog facts
;;;; Auto-generated by Hugo {{ hugo.Version }} on {{ now.Format "2006-01-02" }}
;;;; Source: hugo/layouts/index.lisp + hugo/data/author.yaml + hugo/content/posts/
;;;;
;;;; Do not edit directly — update hugo/data/author.yaml or post front matter.
;;;; Regenerate: hugo --gc (runs on every site build)
;;;;
;;;; This file implements the dsc/corpus package (see package.lisp).
;;;; It is loaded as part of the DwightASpencerCom ASDF system:
;;;;
;;;;   (ql-dist:install-dist "http://dwightaspencer.com/distinfo.txt" :prompt nil)
;;;;   (ql:quickload :DwightASpencerCom)
;;;;
;;;; Public entry points are in dwightaspencer.lisp (DwightASpencerCom package):
;;;;   (DwightASpencerCom:query '(tag ?s :privacy))
;;;;   (DwightASpencerCom:find-post "03-rules-types-and-glue")
;;;;   (DwightASpencerCom:all-posts)
;;;;
;;;; Within dsc/corpus, dsc/logic is available as the local nickname 'logic'
;;;; per (:local-nicknames (#:logic #:dsc/logic)) in package.lisp.

(named-readtables:in-readtable :standard)
(in-package #:dsc/corpus)

(defconstant +dist-root+    "{{ .Site.Params.canonicalBase }}")
(defconstant +search-index+ "{{ .Site.Params.canonicalBase }}/pagefind/pagefind.js")
(defconstant +corpus-url+   "{{ .Site.Params.canonicalBase }}/corpus.lisp")
(defconstant +build-date+   "{{ now.Format "2006-01-02" }}")

;;;; ── Fact assertion ──────────────────────────────────────────────────────────
;;;; Fact schemas (mirrors ml-prolog-pokemon catalog approach):
;;;;   (post   slug title date word-count)
;;;;   (tag    slug keyword)
;;;;   (author slug orcid)
;;;;   (artifact name descriptor path)   ; Easter egg / metadata artifacts
;;;;   (diagram slug index title alt-text) ; Mermaid diagrams embedded in post
;;;;   (related  slug target label)          ; related_post front matter cross-reference
;;;;   (page     slug title section date)    ; all non-post pages (policy, now, uses, etc.)

(defun assert-post-facts (db)
  "Assert all post, tag, author, and artifact facts into DB.
   DB must be a prolog-db created by logic:make-post-kb.
   Returns DB.
   Generated from {{ len (where .Site.RegularPages "Section" "posts") }} posts."
  ;; pf = assert a prolog fact into db (shorthand for logic:db-assert)
  (flet ((pf (&rest fact) (logic:db-assert db fact)))
{{ range (where .Site.RegularPages "Section" "posts").ByDate.Reverse -}}
{{- $slug := .Slug }}
    ;; {{ .Title }}
    (pf 'post {{ printf "%q" $slug }}
        {{ printf "%q" .Title }}
        {{ printf "%q" (.Date.Format "2006-01-02") }}
        {{ .WordCount }})
{{ range .Params.tags -}}
    (pf 'tag {{ printf "%q" $slug }} :{{ . | lower | replaceRE "[^a-z0-9]" "-" }})
{{ end -}}
    (pf 'author {{ printf "%q" $slug }} "{{ $.Site.Data.author.orcid }}")
{{ range $i, $d := .Params.diagrams -}}
    (pf 'diagram {{ printf "%q" $slug }} {{ $i }}
        {{ printf "%q" (default "" $d.title) }}
        {{ printf "%q" (default "" $d.alt) }})
{{ end -}}
{{ with .Params.related_post -}}
    (pf 'related {{ printf "%q" $slug }}
        {{ printf "%q" .slug }}
        {{ printf "%q" .label }})
{{ end -}}
{{ end }}

{{/* Non-post pages: policy, now, uses, projects, media, series, taxonomy */}}
{{ range (where .Site.RegularPages "Section" "!=" "posts") -}}
  {{- $slug    := .Params.slug | default .File.BaseFileName -}}
  {{- $section := .Section | default "root" -}}
  {{- $date    := .Date.Format "2006-01-02" -}}
  (pf 'page {{ printf "%q" $slug }}
      {{ printf "%q" .Title }}
      {{ printf "%q" $section }}
      {{ printf "%q" $date }})
{{ end }}
  )
  db)

;;;; ── Knowledge base construction ────────────────────────────────────────────

(defun make-site-kb ()
  "Construct and return the site knowledge base.
   Asserts all post/tag/author facts plus static artifact facts.
   Called by DwightASpencerCom:make-kb in dwightaspencer.lisp —
   use that for the public API rather than calling this directly.
   Returns the populated prolog-db."
  (let ((db (assert-post-facts (logic:make-post-kb))))
    ;; ── Static artifact facts ────────────────────────────────────────────────
    ;; These are not generated from post front matter — they are manually
    ;; asserted here. Discoverable via: (DwightASpencerCom:query '(tag ?s :bbs))
    ;;
    ;; /.well-known/file_id.diz — raw ANSI splash from XM Core BBS
    ;; SAUCE header intact. IBM VGA. 20160503. dz tag. It is well known.
    (logic:db-assert db '(artifact "file_id.diz" :bbs-descriptor "/.well-known/file_id.diz"))
    (logic:db-assert db '(tag "file_id.diz" :bbs))
    (logic:db-assert db '(tag "file_id.diz" :ansi-art))
    db))

;;;; ── Corpus query functions ──────────────────────────────────────────────────
;;;; These take an explicit KB argument — they are the corpus layer's API.
;;;; The DwightASpencerCom package wraps these with a *kb* cache and
;;;; single-argument convenience functions (see dwightaspencer.lisp).

(defun find-post (kb slug)
  "Return a plist for post SLUG in KB, or NIL if not found.
   Plist keys: :slug :title :date :words"
  (let ((env (logic:db-prove-first kb `(post ,slug ?title ?date ?wc))))
    (when env
      (list :slug  slug
            :title (cdr (assoc '?title env))
            :date  (cdr (assoc '?date  env))
            :words (cdr (assoc '?wc    env))))))

(defun find-by-tag (kb tag)
  "Return a list of post slugs tagged with TAG in KB.
   TAG should be a keyword, e.g. :privacy, :bbs, :ansi-art"
  (logic:db-var-all kb `(tag ?slug ,tag) '?slug))

(defun all-posts (kb)
  "Return a list of all post slugs in KB."
  (logic:db-var-all kb '(post ?slug ?title ?date ?wc) '?slug))

(defun all-tags (kb)
  "Return a deduplicated list of all tag keywords in KB."
  (remove-duplicates
   (logic:db-var-all kb '(tag ?slug ?tag) '?tag)
   :test #'equal))

(defun post-diagrams (kb slug)
  "Return a list of diagram plists for post SLUG in KB.
   Each plist has keys: :index :title :alt
   Returns NIL if the post has no diagrams."
  (mapcar (lambda (env)
            (list :index (cdr (assoc '?i   env))
                  :title (cdr (assoc '?t   env))
                  :alt   (cdr (assoc '?alt env))))
          (logic:db-prove-all kb `(diagram ,slug ?i ?t ?alt))))

(defun all-diagrams (kb)
  "Return a list of all diagram facts in KB as plists.
   Keys: :slug :index :title :alt"
  (mapcar (lambda (env)
            (list :slug  (cdr (assoc '?slug env))
                  :index (cdr (assoc '?i    env))
                  :title (cdr (assoc '?t    env))
                  :alt   (cdr (assoc '?alt  env))))
          (logic:db-prove-all kb '(diagram ?slug ?i ?t ?alt))))

(defun post-related (kb slug)
  "Return a plist for the related post of SLUG in KB, or NIL.
   Plist keys: :target :label
   Only returns a value if SLUG has a related_post front matter entry."
  (let ((env (logic:db-prove-first kb `(related ,slug ?target ?label))))
    (when env
      (list :target (cdr (assoc '?target env))
            :label  (cdr (assoc '?label  env))))))

(defun posts-related-to (kb target-slug)
  "Return a list of slugs whose related_post points at TARGET-SLUG.
   Enables reverse traversal: find all posts that cite a given post."
  (logic:db-var-all kb `(related ?slug ,target-slug ?label) '?slug))

(defun all-related (kb)
  "Return all (related slug target label) facts as plists.
   Keys: :slug :target :label
   Enables full graph traversal of the post relationship network."
  (mapcar (lambda (env)
            (list :slug   (cdr (assoc '?slug   env))
                  :target (cdr (assoc '?target env))
                  :label  (cdr (assoc '?label  env))))
          (logic:db-prove-all kb '(related ?slug ?target ?label))))

(defun all-pages (kb)
  "Return all non-post pages in KB as plists. Keys: :slug :title :section :date"
  (mapcar (lambda (env)
            (list :slug    (cdr (assoc '?slug    env))
                  :title   (cdr (assoc '?title   env))
                  :section (cdr (assoc '?section env))
                  :date    (cdr (assoc '?date    env))))
          (logic:db-prove-all kb '(page ?slug ?title ?section ?date))))

(defun find-page (kb slug)
  "Find a non-post page by slug. Returns plist or NIL."
  (let ((env (logic:db-prove-first kb `(page ,slug ?title ?section ?date))))
    (when env
      (list :slug    slug
            :title   (cdr (assoc '?title   env))
            :section (cdr (assoc '?section env))
            :date    (cdr (assoc '?date    env))))))
