;;;; corpus-stub.lisp — bundled stub for DwightASpencerCom system
;;;;
;;;; Implements the dsc/corpus package as a source file in the ASDF system.
;;;; The Hugo-generated corpus.lisp replaces this at build time with live
;;;; post facts asserted into the knowledge base; this stub provides a
;;;; loadable fallback for REPL use and testing.
;;;;
;;;; Package hierarchy:
;;;;   dsc/logic        — micro-Prolog engine (make-post-kb, db-assert, etc.)
;;;;   dsc/corpus       — THIS FILE — post/tag/author facts (uses dsc/logic)
;;;;   dsc/render       — PostScript output (uses dsc/corpus)
;;;;   DwightASpencerCom — top-level; ql:quickload target; uses all three
;;;;
;;;; Local nickname: within dsc/corpus, dsc/logic is available as 'logic'
;;;; per (:local-nicknames (#:logic #:dsc/logic)) in package.lisp.

(in-package #:dsc/corpus)

;;; ── Site configuration constants ──────────────────────────────────────────

(defparameter +dist-root+
  "https://dwightaspencer.com"
  "Canonical base URL for dwightaspencer.com.
Used to construct absolute URLs for posts and assets.")

(defparameter +search-index+
  "https://dwightaspencer.com/pagefind/pagefind.js"
  "URL of the Pagefind JavaScript search index bundle.
Load this in a browser to enable client-side full-text search.")

(defparameter +corpus-url+
  "https://dwightaspencer.com/corpus.lisp"
  "URL of the live Quicklisp-loadable corpus.
Fetched on demand when the bundled corpus.lisp is absent.")

;;; ── Corpus population ─────────────────────────────────────────────────────

(defun assert-post-facts (kb)
  "Assert all site post facts into KB.
In the stub, this is a no-op — the live corpus.lisp generated by Hugo
overrides this function with actual (post ...), (tag ...), (author ...)
assertions. KB is returned unchanged.

See also: make-site-kb, which calls this automatically."
  (declare (ignore kb))
  nil)

;;; ── Knowledge base construction ───────────────────────────────────────────

(defun make-site-kb ()
  "Create and populate the site knowledge base.
Returns a dsc/logic:prolog-db populated with post, tag, and author
facts from the corpus. In CI builds, corpus.lisp is generated by Hugo
and bundled into the ASDF system tarball; in REPL use without a local
corpus, falls back to fetching the live corpus via HTTP.

Example:
  (let ((kb (dsc/corpus:make-site-kb)))
    (dsc/corpus:find-post kb \"01-a-better-tweedy-bird\"))"
  (let ((db (logic:make-post-kb)))
    (handler-case
        (progn
          (unless (fboundp 'assert-post-facts)
            (format *debug-io* "~&; Fetching corpus from ~A~%" +corpus-url+)
            (load +corpus-url+))
          (assert-post-facts db))
      (error (e)
        (format *debug-io* "~&; Warning: could not load corpus: ~A~%~
                             ; Using empty knowledge base.~%" e)))
    db))

;;; ── Corpus query functions ────────────────────────────────────────────────

(defun find-post (kb slug)
  "Find a post in KB by SLUG. Returns a plist with keys :slug, :title,
:date, :words, or NIL if not found.

Example:
  (find-post kb \"03-rules-types-and-glue\")
  ;; => (:slug \"03-rules-types-and-glue\" :title \"Rules, Types, and Glue\"
  ;;     :date \"2026-01-15\" :words 1200)"
  (let ((env (logic:db-prove-first kb `(post ,slug ?title ?date ?words))))
    (when env
      (list :slug  slug
            :title (cdr (assoc '?title env))
            :date  (cdr (assoc '?date  env))
            :words (cdr (assoc '?words env))))))

(defun find-by-tag (kb tag)
  "Return a list of post slugs in KB that carry TAG (a keyword).
Returns an empty list if no posts have the tag.

Example:
  (find-by-tag kb :privacy)
  ;; => (\"00-hellowrld\" \"04-watchers-you-fed\" ...)"
  (logic:db-var-all kb `(tag ?slug ,tag) '?slug))

(defun all-posts (kb)
  "Return a list of all post slugs present in KB.

Example:
  (all-posts kb)
  ;; => (\"00-hellowrld\" \"01-a-better-tweedy-bird\" ...)"
  (logic:db-var-all kb '(post ?slug ?title ?date ?wc) '?slug))

(defun all-tags (kb)
  "Return a de-duplicated list of all tag keywords in KB.

Example:
  (all-tags kb)
  ;; => (:privacy :security :foss :devops ...)"
  (remove-duplicates
   (logic:db-var-all kb '(tag ?slug ?tag) '?tag)))
