;;;; corpus-stub.lisp — bundled stub for DwightASpencerCom system
;;;;
;;;; Implements the com.dwightaspencer/corpus package as a source file in the ASDF system.
;;;; The Hugo-generated corpus.lisp replaces this at build time with live
;;;; post facts asserted into the knowledge base; this stub provides a
;;;; loadable fallback for REPL use and testing.
;;;;
;;;; Package hierarchy:
;;;;   com.dwightaspencer/logic   — micro-Prolog engine (make-post-kb, db-assert, etc.)
;;;;   com.dwightaspencer/corpus  — THIS FILE — post/tag/author facts (uses com.dwightaspencer/logic)
;;;;   com.dwightaspencer/render  — PostScript output (uses com.dwightaspencer/corpus)
;;;;   DwightASpencerCom — top-level; ql:quickload target; uses all three
;;;;
;;;; Local nickname: within com.dwightaspencer/corpus, com.dwightaspencer/logic is available as 'logic'
;;;; per (:local-nicknames (#:logic #:com.dwightaspencer/logic)) in package.lisp.

(in-package #:com.dwightaspencer/corpus)

;;; ── Site configuration constants ──────────────────────────────────────────

(defparameter +dist-root+
  "https://dwightaspencer.com"
  "Canonical base URL for dwightaspencer.com.
Used to construct absolute URLs for posts and assets.")

(defparameter +search-index+
  "https://dwightaspencer.com/pagefind/pagefind.js"
  "URL of the Pagefind JavaScript search index bundle.
Load this in a browser to enable client-side full-text search.")

(defparameter +corpus-url+
  "https://dwightaspencer.com/corpus.lisp"
  "URL of the live Quicklisp-loadable corpus.
Fetched on demand when the bundled corpus.lisp is absent.")

;;; ── Corpus population ─────────────────────────────────────────────────────

(defun assert-post-facts (kb)
  "Assert all site post facts into KB.
In the stub, this is a no-op — the live corpus.lisp generated by Hugo
overrides this function with actual (post ...), (tag ...), (author ...)
assertions. KB is returned unchanged.

See also: make-site-kb, which calls this automatically."
  (declare (ignore kb))
  nil)

;;; ── Knowledge base construction ───────────────────────────────────────────

(defun make-site-kb ()
  "Create and populate the site knowledge base.
Returns a com.dwightaspencer/logic:prolog-db populated with post, tag, and author
facts. In the CI-built Quicklisp tarball, corpus.lisp is the Hugo-
generated file with a real assert-post-facts. This stub ships a noop
assert-post-facts as a fallback so the system loads without the
tarball, but the KB will be empty until the real corpus is loaded.

To get a populated KB without the Quicklisp tarball, use
load-live-corpus (requires dexador):

  (ql:quickload :dexador)
  (com.dwightaspencer/corpus:load-live-corpus)

Example:
  (let ((kb (com.dwightaspencer/corpus:make-site-kb)))
    (com.dwightaspencer/corpus:all-posts kb))"
  (let ((db (logic:make-post-kb)))
    (assert-post-facts db)
    db))

(defun load-live-corpus (&optional (url +corpus-url+))
  "Fetch the live corpus from URL using dexador, eval it into the current
image, and return a freshly populated knowledge base.

Requires dexador (available via Quicklisp):
  (ql:quickload :dexador)

URL defaults to +corpus-url+ (https://dwightaspencer.com/corpus.lisp).
Returns a prolog-db with all post/tag/author facts asserted.
Signals an error if dexador is not loaded or the fetch fails.

Example:
  (ql:quickload :dexador)
  (let ((kb (com.dwightaspencer/corpus:load-live-corpus)))
    (com.dwightaspencer/corpus:all-posts kb))"
  (unless (find-package :dexador)
    (error "dexador is not loaded. Run (ql:quickload :dexador) first."))
  (let ((src (funcall (intern "GET" :dexador) url)))
    (with-input-from-string (s src)
      (loop for form = (read s nil s)
            until (eq form s)
            do (eval form))))
  (make-site-kb))

;;; ── Corpus query functions ────────────────────────────────────────────────

(defun find-post (kb slug)
  "Find a post in KB by SLUG. Returns a plist with keys :slug, :title,
:date, :words, or NIL if not found.

Example:
  (find-post kb \"03-rules-types-and-glue\")
  ;; => (:slug \"03-rules-types-and-glue\" :title \"Rules, Types, and Glue\"
  ;;     :date \"2026-01-15\" :words 1200)"
  (let ((env (logic:db-prove-first kb `(post ,slug ?title ?date ?words))))
    (when env
      (list :slug  slug
            :title (cdr (assoc '?title env))
            :date  (cdr (assoc '?date  env))
            :words (cdr (assoc '?words env))))))

(defun find-by-tag (kb tag)
  "Return a list of post slugs in KB that carry TAG (a keyword).
Returns an empty list if no posts have the tag.

Example:
  (find-by-tag kb :privacy)
  ;; => (\"00-hellowrld\" \"04-watchers-you-fed\" ...)"
  (logic:db-var-all kb `(tag ?slug ,tag) '?slug))

(defun all-posts (kb)
  "Return a list of all post slugs present in KB.

Example:
  (all-posts kb)
  ;; => (\"00-hellowrld\" \"01-a-better-tweedy-bird\" ...)"
  (logic:db-var-all kb '(post ?slug ?title ?date ?wc) '?slug))

(defun all-tags (kb)
  "Return a de-duplicated list of all tag keywords in KB.

Example:
  (all-tags kb)
  ;; => (:privacy :security :foss :devops ...)"
  (remove-duplicates
   (logic:db-var-all kb '(tag ?slug ?tag) '?tag)))
